In [2]:
import numpy as np

In [3]:
numbers = [1,2,3,4,5,6,7,8,9]

In [4]:
np.mean(numbers)

5.0

In [5]:
np.median(numbers)

5.0

In [6]:
np.std(numbers)

2.5819888974716112

In [8]:
array = np.array([1,4,5,8], float)
print array
print ""
array = np.array([[1,2,3],[4,5,6,]], float)
print array
print "Next........."

[ 1.  4.  5.  8.]

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
Next.........


In [10]:
two_D_array = np.array([[1, 2, 3], [4, 5, 6]], float)
print two_D_array
print ""
print two_D_array[1][1]
print ""
print two_D_array[1, :]
print ""
print two_D_array[:, 2]

[[ 1.  2.  3.]
 [ 4.  5.  6.]]

5.0

[ 4.  5.  6.]

[ 3.  6.]


In [11]:
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([5, 2, 6], float)
print array_1 + array_2
print ""
print array_1 - array_2
print ""
print array_1 * array_2

[ 6.  4.  9.]

[-4.  0. -3.]

[  5.   4.  18.]


In [12]:
array_1 = np.array([[1, 2], [3, 4]], float)
array_2 = np.array([[5, 6], [7, 8]], float)
print array_1 + array_2
print ""
print array_1 - array_2
print ""
print array_1 * array_2

[[  6.   8.]
 [ 10.  12.]]

[[-4. -4.]
 [-4. -4.]]

[[  5.  12.]
 [ 21.  32.]]


In [13]:
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([[6], [7], [8]], float)
print np.mean(array_1)
print np.mean(array_2)
print ""
print np.dot(array_1, array_2)

2.0
7.0

[ 44.]
